### ISSUE TITLE
Why does exBankID require Poison 3.1 and not 4.x?

### ISSUE THREAD

**Issue by Preen** [anfly0/exBankID#21]

**Comment by anfly0** [comment]
@Preen Thank you for opening this issue. 
This is most likely an oversite on my part that should be simple to fix.
If you feel up for it you are more than welcome to fork this repo, bump the poison version and open a PR to master.
If not I will do my best to get around to it this weekend!

And thanks for the star!

**Comment by anfly0** [comment]
@Preen Version 0.2.2 is now released. This means that it will be possible to use poison v4.x without any dependency conflicts from now on.
