### ISSUE TITLE
Support for requirement parameter 

### ISSUE THREAD

**Issue by anfly0** [anfly0/exBankID#9]
Add support for the requirement parameter [14.5](https://www.bankid.com/assets/bankid/rp/bankid-relying-party-guidelines-v3.4.pdf)

- Should be added to the Authentication and Sign payload structs.
- Convenience methods constructing a valid "requirements map".

**Comment by davemenninger** [comment]
I think I've got this mostly working in the Auth payload: https://github.com/anfly0/exBankID/compare/master...davemenninger:support-requirement-parameter

@anfly0 Can you let me know if this approach seems good?  If so, I can continue onward with the Sign payload.

Also, can you give me an example of how you'd see a convenience method for the requirements map would work?

**Comment by anfly0** [comment]
@davemenninger At first glance, this looks great!
I will take a closer look and run some tests as soon as possible.
Whenever you feel ready, please open a PR, and I will get back to you if there is anything that needs to be changed.

The convenience methods are not a hard requirement for this issue.
The general idea is to have a set of composable functions that can be used to construct a  "requirements map".
Example:
```elixir
%{"certificatePolicies":["1.2.752.78.1.1", "1.2.752.71.1.2", "1.2.752.78.1.5"], "tokenStartRequired":true} =
certificate_policies(%{}, :bank_id_on_file)
|> certificate_policies(:bank_id_on_smart_card)
|> certificate_policies(:mobile_bank_id)
|> token_start_required(:true)
```
